version: "3.7"

services:

  postgres:
    container_name: juddith_postgres
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./docker/config/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/data/postgres:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: juddith_redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge