# Generated by Django 2.2 on 2019-04-27 04:06

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elocution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elocution_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'elocution',
                'verbose_name_plural': 'elocutions',
            },
            bases=(models.Model, application.models.BaseAppModel),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('call', models.CharField(max_length=200, verbose_name='call')),
                ('error_message', models.CharField(blank=True, max_length=200, null=True, verbose_name='error message')),
                ('empty_message', models.CharField(blank=True, max_length=200, null=True, verbose_name='empty message')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
            bases=(models.Model, application.models.BaseAppModel),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('elocutions', models.ManyToManyField(related_name='elocution_responses', to='application.Elocution')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
            },
            bases=(models.Model, application.models.BaseAppModel),
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('tag', models.SlugField(unique=True, verbose_name='tag')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Feature', verbose_name='Feature')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Response', verbose_name='response')),
            ],
            options={
                'verbose_name': 'intent',
                'verbose_name_plural': 'intentions',
            },
            bases=(models.Model, application.models.BaseAppModel),
        ),
        migrations.AddField(
            model_name='elocution',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Intent'),
        ),
        migrations.AddField(
            model_name='elocution',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elocution_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
    ]
